config:
history:
logbook:
sun:

# Enable VSCode debugging
debugpy:
## start and wait = true will force HA to stop and wait for a debugger attachment during boot to test initialization of plugins
  start: true
  wait: true
  host: localhost
  port: 6789

logger:
  default: info
  logs:
    custom_components.aula: debug